pipeline:
  build:
    image: node:6
    commands:
      - apt-get update
      - apt-get install -y git build-essential gcc g++
      - git clone https://framagit.org/bnjbvr/kresus.git app
      - cd app
      - make install-node-dev-deps build lint

  publish:
    image: plugins/docker
    registry: no-cloud
    repo: no-cloud.fr/maestro/kresus
    tag: latest
    file: Dockerfile
