pipeline:
  build:
    image: node:6
    commands:
      - apt-get update
      - apt-get install -y git build-essential gcc g++
      - git clone https://framagit.org/bnjbvr/kresus.git app
      - make install-node-dev-deps build lint
